### ISSUE TITLE
On MacOS 14.5 i get compiler error

### ISSUE THREAD

**Issue by jczmok-iag** [AndersBNielsen/65uino#4]
I get compiler error when trying to compile the code:

`ca65 -vvv --cpu 6502 -l  build/listing.txt -o  build/abn6507rom.o abn6507rom.s        
abn6507rom.s(799): Error: Unexpected trailing garbage characters`

**Comment by AndersBNielsen** [comment]
Whoops! My bad - had some extra spaces there. 
Fixed with latest commit.
